import Head from 'next/head';
import Footer from '../../components/organisms/Footer';
import LokakaryaPage from '../../components/organisms/LokakaryaPage';
import Navbar from '../../components/organisms/Navbar';

const lokakarya = () => {
  return (
    <>
      <Head>
        <title>Lokakarya Kalimastu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar activeMenu="lokakarya" />
      <LokakaryaPage />
      <Footer />
    </>
  );
};

export default lokakarya;
