import Head from 'next/head';
import Footer from '../../components/organisms/Footer';
import Navbar from '../../components/organisms/Navbar';
import ProductPage from '../../components/organisms/ProductPage';

const produk = () => {
  return (
    <>
      <Head>
        <title>Produk Kalimastu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar activeMenu="produk" />
      <ProductPage />
      <Footer />
    </>
  );
};

export default produk;
