import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styled from 'styled-components';

const ProductContentSection = styled.section`
  padding: 0 20px;
  margin-bottom: 100px;
`;

const ArrowBack = styled.img`
  margin: 20px 0;
  width: 30px;
`;

const ImageContainer = styled.div`
  width: calc(100vw - 40px);
  height: calc(100vw - 40px);
  border-radius: 20px;
  overflow: hidden;
`;

const ProductName = styled.h1`
  margin-top: 10px;
  margin-bottom: 5px;
`;

const ProductBy = styled.p`
  color: #8e8e8e;
`;

const TokoContainer = styled.div`
  width: 100%;
  display: flex;
  justify-content: space-between;
  margin: 20px 0;
`;

const Toko = styled.div`
  width: 60px;
  height: 60px;
  border-radius: 10px;
  overflow: hidden;
`;

const Deskripsi = styled.div`
  margin: 20px 0;
`;

const AttentionContainer = styled.div`
  padding: 20px;
  position: fixed;
  bottom: 0;

  h6 {
    text-align: center;
    padding: 10px 20px;
    width: 100%;
    border-radius: 30px;
    background-color: #ffd055;

    span {
      font-weight: 700;
    }
  }
`;

const produk = () => {
  return (
    <>
      <Head>
        <title>Sandal dan Sepatu Kulit Grandable.id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductContentSection>
        <Link href="/produk" passHref>
          <ArrowBack src="/assets/icon/arrow_left.svg" alt="" />
        </Link>

        <ImageContainer>
          <Image
            src="/assets/img/grandable_sendal_slop.jpg"
            width={1080}
            height={1080}
          />
        </ImageContainer>
        <ProductName>Sandal dan Sepatu Kulit Grandable.id</ProductName>
        <ProductBy>by Grandable.id</ProductBy>
        <TokoContainer>
          <a href="https://shopee.co.id/grandable" target="_blank">
            <Toko>
              <Image
                src="/assets/icon/shopee.jpg"
                width={60}
                height={60}
                objectFit="cover"
              />
            </Toko>
          </a>
        </TokoContainer>
        <Deskripsi>
          <h1>Deskripsi</h1>
          <p>Grandable Ini Mengeluarkan Berbagai Flatshoes yang Membuat</p>
          <p>
            Penampilan Kamu Semakin Fashionable dan Stylish. Produk Fashion ini
            Semakin Sempurna dengan Material Kulit asli dan Model Desain yang
            simple serta Elegan. Flatshoes ini Nyaman dan Ringan. Sehingga Kamu
            dapat Tampil Gaya sekaligus Nyaman Beraktivitas Seharian.
          </p>
          <br />
          <br />
          <p>
            size chart
            <br />
            <br />
            36 : 21 cm
            <br />
            37 : 22 cm
            <br />
            38 : 23 cm
            <br />
            39 : 24 cm
            <br />
            40 : 25 cm
            <br />
            41 : 26 cm
          </p>
        </Deskripsi>
      </ProductContentSection>
      <AttentionContainer>
        <h6>
          Produk ini bisa didapatkan di stand bazar
          <span>KALIMASTU ITG</span>
        </h6>
      </AttentionContainer>
    </>
  );
};

export default produk;
